"""Persistence: named profiles, last-applied state, and login autostart."""

from __future__ import annotations

import json
import os
import stat
import sys

from .device import Profile, REGIONS, ZoneState

CONFIG_DIR = os.path.join(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")), "msikey"
)
PROFILES_PATH = os.path.join(CONFIG_DIR, "profiles.json")
STATE_PATH = os.path.join(CONFIG_DIR, "state.json")
# The last state that had at least one lit zone - what the power toggle and
# `msikey on` return to after the backlight has been switched off.
LIT_PATH = os.path.join(CONFIG_DIR, "last-lit.json")

AUTOSTART_DIR = os.path.join(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config")), "autostart"
)
AUTOSTART_PATH = os.path.join(AUTOSTART_DIR, "msikey-restore.desktop")
WRAPPER_PATH = os.path.join(CONFIG_DIR, "apply-last.sh")


def _ensure_dir() -> None:
    os.makedirs(CONFIG_DIR, exist_ok=True)


def _default_profiles() -> dict[str, Profile]:
    red = Profile(name="Solid red", mode="normal",
                  zones={r: ZoneState("red", "high") for r in REGIONS})
    rgb = Profile(name="RGB split", mode="normal", zones={
        "left": ZoneState("red", "high"),
        "middle": ZoneState("green", "high"),
        "right": ZoneState("blue", "high"),
    })
    breathe = Profile(name="Breathe purple/cyan", mode="breathe", zones={
        "left": ZoneState("purple", "high"),
        "middle": ZoneState("sky", "high"),
        "right": ZoneState("purple", "high"),
    })
    off = Profile(name="Off", mode="normal",
                  zones={r: ZoneState("off", "high") for r in REGIONS})
    return {p.name: p for p in (rgb, red, breathe, off)}


# --------------------------------------------------------------------------- #
# profiles
# --------------------------------------------------------------------------- #
def load_profiles() -> dict[str, Profile]:
    try:
        raw = json.load(open(PROFILES_PATH))
        profiles = {
            str(name): Profile.from_dict(d) for name, d in raw.get("profiles", {}).items()
        }
        if profiles:
            return profiles
    except (OSError, ValueError):
        pass
    return _default_profiles()


def save_profiles(profiles: dict[str, Profile]) -> None:
    _ensure_dir()
    tmp = PROFILES_PATH + ".tmp"
    with open(tmp, "w") as f:
        json.dump({"profiles": {n: p.to_dict() for n, p in profiles.items()}}, f, indent=2)
    os.replace(tmp, PROFILES_PATH)


# --------------------------------------------------------------------------- #
# last-applied state
# --------------------------------------------------------------------------- #
def load_state() -> Profile:
    try:
        return Profile.from_dict(json.load(open(STATE_PATH)))
    except (OSError, ValueError):
        return _default_profiles()["RGB split"]


def _write_profile(path: str, profile: Profile) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        json.dump(profile.to_dict(), f, indent=2)
    os.replace(tmp, path)


def save_state(profile: Profile) -> None:
    """Persist the last-applied state, and (if lit) the last-lit state too."""
    _ensure_dir()
    _write_profile(STATE_PATH, profile)
    if profile.is_lit():
        _write_profile(LIT_PATH, profile)


def load_last_lit() -> Profile:
    """The colours to restore when switching the backlight back on."""
    try:
        p = Profile.from_dict(json.load(open(LIT_PATH)))
        if p.is_lit():
            return p
    except (OSError, ValueError):
        pass
    current = load_state()
    return current if current.is_lit() else _default_profiles()["RGB split"]


# --------------------------------------------------------------------------- #
# login autostart ("restore on login")
# --------------------------------------------------------------------------- #
def _package_root() -> str:
    # parent directory that contains the `msikey` package
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def autostart_enabled() -> bool:
    return os.path.isfile(AUTOSTART_PATH)


def set_autostart(enabled: bool) -> None:
    if not enabled:
        for p in (AUTOSTART_PATH, WRAPPER_PATH):
            try:
                os.remove(p)
            except OSError:
                pass
        return

    _ensure_dir()
    os.makedirs(AUTOSTART_DIR, exist_ok=True)
    wrapper = (
        "#!/bin/sh\n"
        "# Generated by MSIKey - restores the last applied keyboard lighting.\n"
        f'export PYTHONPATH="{_package_root()}${{PYTHONPATH:+:$PYTHONPATH}}"\n'
        f'exec "{sys.executable}" -m msikey apply --last\n'
    )
    with open(WRAPPER_PATH, "w") as f:
        f.write(wrapper)
    os.chmod(WRAPPER_PATH, os.stat(WRAPPER_PATH).st_mode | stat.S_IEXEC | stat.S_IXGRP)

    desktop = (
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=MSIKey - restore keyboard lighting\n"
        f"Exec={WRAPPER_PATH}\n"
        "NoDisplay=true\n"
        "X-GNOME-Autostart-enabled=true\n"
        "X-GNOME-Autostart-Delay=2\n"
    )
    with open(AUTOSTART_PATH, "w") as f:
        f.write(desktop)
